### ISSUE TITLE
dx

### ISSUE THREAD

**Issue by Ljcasdasd** [Passer1072/RookieAI_yolov8#10]

**Comment by Ljcasdasd** [comment]
dxcam 无法运行
Exception in thread BetterCam:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\bettercam\bettercam.py", line 213, in __capture
    self.stop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\bettercam\bettercam.py", line 147, in stop
    self.__thread.join(timeout=10)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1050, in join
    raise RuntimeError("cannot join current thread")
0: 640x640 (no detections), 5.0ms
RuntimeError: cannot join current thread
Speed: 3.0ms preprocess, 5.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
[]

**Comment by Ljcasdasd** [comment]
是join用错了还是啥问题

**Comment by Passer1072** [comment]
我没能复现出该问题,注释掉`thread1.join()`试试，或者使用v2.3之前的版本(v2.2.4)测试下，2.2.4版本没有使用betterCam这个库应该没有问题。
