### ISSUE TITLE
没运行成功

### ISSUE THREAD

**Issue by zwbs66** [Passer1072/RookieAI_yolov8#68]
![Uploading 17312245190752911960140846799767.jpg…]()
大佬帮帮我

**Comment by zwbs66** [comment]
图片上传失败了
PS C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8> ./RookieAI_YOLOv8.exe
Traceback (most recent call last):
  File "RookieAI_YOLOv8.py", line 7, in <module>
  File "C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8\_internal\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8\_internal\urllib3\__init__.py", line 5, in <module>
    from __future__ import annotations
ModuleNotFoundError: No module named '__future__'
[PYI-16236:ERROR] Failed to execute script 'RookieAI_YOLOv8' due to unhandled exception!
PS C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8>

**Comment by zwbs66** [comment]
Suggestion [3,General]: The command RookieAI_YOLOv8.exe was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\RookieAI_YOLOv8.exe". See "get-help about_Command_Precedence" for more details.        
PS C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8> ./RookieAI_YOLOv8.exe
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "RookieAI_YOLOv8.py", line 18, in <module>
  File "C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8\_internal\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8\_internal\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
    if sys.path[0] == BASE_DIR or os.path.realpath(sys.path[0]) == BASE_DIR:
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import
[PYI-15484:ERROR] Failed to execute script 'RookieAI_YOLOv8' due to unhandled exception!
PS C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8>

**Comment by zwbs66** [comment]
搞错了我电脑是cuda12.4 教程的命令是12.1，现在在重装

**Comment by zwbs66** [comment]
PS C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8> ./RookieAI_YOLOv8.exe         
Traceback (most recent call last):
  File "RookieAI_YOLOv8.py", line 7, in <module>
ModuleNotFoundError: No module named 'requests'
[PYI-8324:ERROR] Failed to execute script 'RookieAI_YOLOv8' due to unhandled exception!
PS C:\Users\lzm\Desktop\RookieAI_yolov8-main\dist\RookieAI_YOLOv8> 


还是不行

**Comment by zwbs66** [comment]
软件包 requests
 
Requests is an HTTP library, written in Python, for human beings. Basic GET usage:
 
>>> import requests
>>> r = requests. get('https:// www. python. org')
>>> r. status_code
200
>>> b'Python is a programming language' in r. content
True
... or POST:
 
>>> payload = dict(key1='value1', key2='value2')
>>> r = requests. post('https:// httpbin. org/ post', data=payload)
>>> print(r. text)
{
  ...
  "form": {
    "key1": "value1",
    "key2": "value2"
  },
  ...
}
The other HTTP methods are supported - see requests. api. Full documentation is at <https:// requests. readthedocs. io  >.


我已经安装了这个模块但是还不行

**Comment by molanp** [comment]
不要使用pyinstaller打包程序 使用`python xxx.py`直接运行脚本

**Comment by zwbs66** [comment]
不能打包用吗

**Comment by Passer1072** [comment]
是否有参考 资源后库不完全解决方法
<https://github.com/Passer1072/RookieAI_yolov8/issues/1#issuecomment-2041157885>
 进行操作？

zwbs66 ***@***.***> 于2024年11月10日周日 22:16写道：

**Comment by zwbs66** [comment]
复制了

**Comment by zwbs66** [comment]
D:\RookieAI_yolov8-main\dist\RookieAI_YOLOv8>RookieAI_YOLOv8.exe
开始加载飞易来盒子文件...
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'D:\RookieAI_yolov8-main\dist\RookieAI_YOLOv8\x64_msdk.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "RookieAI_YOLOv8.py", line 2737, in <module>
  File "RookieAI_YOLOv8.py", line 558, in load_DLL
  File "ctypes\__init__.py", line 454, in LoadLibrary
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll './x64_msdk.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[PYI-15588:ERROR] Failed to execute script 'RookieAI_YOLOv8' due to unhandled exception!

D:\RookieAI_yolov8-main\dist\RookieAI_YOLOv8>
x64_msdk.dll这个文件不知道在哪里

**Comment by molanp** [comment]
> 不能打包用吗

目前支持不完善也没有相关教程，还是不要打包使用了，等启动器写好了用启动器就行了

**Comment by zwbs66** [comment]
Exception in thread Thread-2 (main_program_loop):
Traceback (most recent call last):
  File "D:\python\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "D:\python\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\RookieAI_yolov8-main\RookieAI_YOLOv8.py", line 2644, in main_program_loop
    results = model.predict(frame, save=False, conf=confidence, half=half_precision_model, agnostic_nms=True, iou=0.7, classes=[
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\ultralytics\engine\model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\ultralytics\engine\predictor.py", line 169, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\torch\utils\_contextlib.py", line 36, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\ultralytics\engine\predictor.py", line 254, in stream_inference
    with profilers[1]:
  File "D:\python\Lib\site-packages\ultralytics\utils\ops.py", line 51, in __exit__
    self.dt = self.time() - self.start  # delta-time
              ^^^^^^^^^^^
  File "D:\python\Lib\site-packages\ultralytics\utils\ops.py", line 61, in time
    torch.cuda.synchronize(self.device)
  File "D:\python\Lib\site-packages\torch\cuda\__init__.py", line 892, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
cuda版本是12.4运行一会就报错了，不能兼容高版本吗
我的m40没有12.1cuda的版本

**Comment by zwbs66** [comment]
![批注 2024-11-13 114156](https://github.com/user-attachments/assets/a86ffad2-a1d6-4fcd-a916-c141b15b6fbb)
python是311.5

**Comment by zwbs66** [comment]
显卡降了一些频率现在正常使用了
